[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/esp32dev_debug-v0.0.1-main.elf"
firmware = ".pio/build/esp32dev_debug/esp32dev_debug-v0.0.1-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
